Update russian.ts
anime-club/translations pull request #13
Opened 2022-03-04 21:28 UTC by vanja-san

2022-03-05 14:25 UTC, o-alexandrov commented on src/russian.ts
> +  follow: `Отслеживать`,
`Follow` употребляется в смысле подписки на обновления. Предлагаю оставить как было

2022-03-05 14:27 UTC, o-alexandrov commented on src/russian.ts
> +  id: `Индетификатор`,
`id` предлагаю оставить как было из-за популярности термина

2022-03-05 14:39 UTC, o-alexandrov requested changes
Здравствуйте, большое спасибо за Ваш труд и помощь.
По Вашим изменениям:
- использование `ё` вместо `е`
  - некоторые знаменитые создатели [категорично относятся](https://www.artlebedev.ru/kovodstvo/sections/119/) к использованию `ё`
    - мы пообсуждали этот аспект и приняли решение использовать букву `ё` вместо `е`, соглашаясь с Вашим мнением и после прочтения [этого обсуждения](https://dtf.ru/ask/599276-kak-vy-otnosites-k-napisaniyu-bukvy-e-v-internete)     - также, возможно иностранцы захотят изучать русский язык с помощью аниме. Использование `ё` облегчит для них понимание.
- обращение на `вы` вместо `ты`   - согласны с Вами, давайте примем Ваши исправления и начнём всегда использовать Вы
- использование `электронная почта` вместо `email`   - в этом не согласны с Вами, мы считаем для пользователя будет проще прочитать и даже понять слово `email`     - также, почитали об этом в интернете, включая [эту статью](https://technolex.com/ru/new-tips/kak-pravilno-emejl-e-mejl-emejl-imejl-i-mejl-email-e-mail-e-pochta.html), которая предлагает использовать слово `email`   - если Вы хотите продолжить обсуждение этого аспекта, будем рады узнать Ваше мнение

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  follow: `Отслеживать`,
`Follow` употребляется в смысле подписки на обновления. Предлагаю оставить как было

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  id: `Индетификатор`,
`id` предлагаю оставить как было из-за популярности термина

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  enterTheAddressAssociatedWithYourAccount: `Введите адрес, связанный с вашей учётной записью, и мы пришлём вам по электронной почте ссылку для сброса пароля`,
в нескольких строках выше, предлагаю вернуться к `email`, вместо `электронная почта`

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  sendEmail: `Отправить электронное письмо`,
`email / электронное письмо`, пожалуйста используйте `email`

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  username: `Имя пользователя`,
Прошу использовать `Логин`, из-за популярности термина

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  weSentAnEmailTo: `Мы отправили электронное письмо на:`,
`email / электронное письмо`. Пожалуйста, используйте `email`

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  weSentYouANewVerificationEmailPleaseEnterTheCode: `Мы отправили вам новое электронное письмо с подтверждением. Введите код`,
`email / электронное письмо`. Пожалуйста, используйте `email`

2022-03-05 14:39 UTC, o-alexandrov commented on src/russian.ts
> +  yourFeedIsEmpty: `ваша лента пуста`,
Изменилась заглавная буква на строчную. Однако нам, разработчикам, необходимо также использовать заглавную букву программным способом

2022-03-06 00:52 UTC, vanja-san commented
Тогда уже "имейл".
Ну а что если тогда и "учётная запись", оставить как "аккаунт", гугл с этим согласен
![изображение](https://user-images.githubusercontent.com/7201687/156904609-763b8185-d168-4316-8c80-93884c27ef38.png)

2022-03-06 02:10 UTC, vanja-san commented
"Электронное письмо" или "эл. письмо" лучше оставить, совсем не читается "Мы отправили вам имейл(email) на"

2022-03-09 10:38 UTC, merged

2022-03-09 10:39 UTC, o-alexandrov commented
Благодарим за помощь, я внес минимальные правки в соответствии с Вашими рекомендациями